name: Test react & lint

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install
        run: yarn
      - name: lint
        run: yarn lint
      - name: React test
        run: yarn react:test
